### ISSUE TITLE
работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [oleggorina/Skillup#1]
1)
вид не соответствует задаче
![image](https://user-images.githubusercontent.com/8464662/124301063-f563b980-db67-11eb-9029-3c8cc22322bc.png)

2)
некорректный вид
![image](https://user-images.githubusercontent.com/8464662/124301129-0ca2a700-db68-11eb-8d90-04e4cc92e76c.png)

3)
не соответствует задаче
![image](https://user-images.githubusercontent.com/8464662/124301180-1f1ce080-db68-11eb-8b8d-f111e84546e3.png)

**Comment by oleggorina** [comment]
2 ошибка это при каком разрешении ? Никак не могу найти..

**Comment by Alecto** [comment]
Не помню, таскал ширину и нашел

пн, 5 июл. 2021 г., 11:50 oleggorina ***@***.***>:

**Comment by oleggorina** [comment]
Да нашел, проблема была в высоте.
Все исправил, отправить заново ссылки на почту ?

**Comment by Alecto** [comment]
Да

пн, 5 июл. 2021 г., 12:59 oleggorina ***@***.***>:

**Comment by Alecto** [comment]
3 - не исправлено
